#! /usr/bin/env python3

import sys, re, os

def detectVersion(string):
    tmp = re.search(r'\[v(.+?)\]', string)
    
    if (tmp):
        return tmp.group(1)
    return None

version = detectVersion(sys.argv[1])

if (version == None):
    sys.exit(1)

with open('version.txt', 'w', encoding='utf-8') as file:
    file.write("v" + version)
sys.exit(0)

