version: '3.7'

services:
  client_web:
    container_name: area_web
    build:
      context: area_web
      dockerfile: Dockerfile
    ports:
      - '8081:80'
  server:
    container_name: API
    build:
      context: API
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
