service: area
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  memorySize: 512
  timeout: 20
  environment:
    DB_ACCESS_KEY : ${env:DB_ACCESS_KEY}
    DB_SECRET_KEY : ${env:DB_SECRET_KEY}
    API_PORT : ${env:API_PORT}
    GMAIL_USER : ${env:GMAIL_USER}
    GMAIL_PASS : ${env:GMAIL_PASS}
    SECRET : ${env:SECRET}
    WEB_URL : ${env:WEB_URL}
    DISCORD_CLIENT_ID : ${env:DISCORD_CLIENT_ID}
    DISCORD_CLIENT_SECRET : ${env:DISCORD_CLIENT_SECRET}
    DISCORD_TOKEN : ${env:DISCORD_TOKEN}
    TRELLO_KEY: ${env:TRELLO_KEY}
    GITHUB_CLIENT_ID : ${env:GITHUB_CLIENT_ID}
    GITHUB_CLIENT_SECRET : ${env:GITHUB_CLIENT_SECRET}


functions:
  app:
    handler: serverless/serverless.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true