name: Deploy to AWS lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: false
      DB_ACCESS_KEY: ${{ secrets.DB_ACCESS_KEY }}
      DB_SECRET_KEY: ${{ secrets.DB_SECRET_KEY }}
      API_PORT: ${{ secrets.API_PORT }}
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      SECRET: ${{ secrets.SECRET }}
      WEB_URL: ${{ secrets.WEB_URL }}
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
      GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: install node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: install serverless
      run: npm install -g serverless

    - name: configure aws
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: go to api
      run: cd API

    - name: install dependencies
      run: npm i
      working-directory: ./API

      -name: test
        run: env && ls
        working-directory: ./API
    - name: deploy
      run: serverless deploy
      working-directory: ./API