name: Build apk

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: get last commit message
      run: echo "COMMIT_MESSAGE=\"$(git log -1 --pretty=%B | tr '\n' ' ')\"" >> $GITHUB_ENV

    - name: test commit message
      run: |
        if ! ./detectRelease ${{ env.COMMIT_MESSAGE }}; then
          echo "COMMIT_CHECK=1" >> "$GITHUB_ENV"
        else
          echo "COMMIT_CHECK=0" >> "$GITHUB_ENV"
        fi

    - name: set vetsion
      if: env.COMMIT_CHECK == '0'
      run: |
        echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
    
    - name: build
      if: env.COMMIT_CHECK == '0'
      run : |
        cd AreaMobile
        sudo docker build -t build . --file Dockerfile --build-arg EAS_CRED=vnVJu-U6lbRAW-Wx7Z8CP3hSk9Qa5KyHsBqKfPkN --no-cache
        sudo docker run build
        sudo docker ps
        ls build

    - name: login github
      if: env.COMMIT_CHECK == '0'
      run: |
        echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
    
    - name: do release
      if: env.COMMIT_CHECK == '0'
      run: |
        gh release create ${{ env.VERSION }} -t ${{ env.VERSION }} -n ${{ env.VERSION }} -a ./build/* -R AREAJuryExperts/AREA 


    # - name: build
    #   run : sudo docker-compose build --no-cache  client_mobile

    # - name: Stop Docker
    #   run: docker-compose down