name: Build and Deploy to AWS

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Change to area_web directory
      run: cd area_web

    - name: Install dependencies
      run: npm install
      working-directory: ./area_web

    - name: Build React app
      run: npm run build
      working-directory: ./area_web

    # Ajoutez ici les autres étapes nécessaires pour le déploiement sur AWS
