name: Build and Deploy to AWS

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CI: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1' # Changez cela selon votre région AWS
      S3_BUCKET: 'areafront' # Remplacez par le nom de votre bucket S3

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Change to area_web directory
      run: cd area_web

    - name: Install dependencies
      run: npm install
      working-directory: ./area_web

    - name: Build React app
      run: npm run build
      working-directory: ./area_web

    - name: Deploy to S3
      run: |
        aws s3 sync ./area_web/build s3://$S3_BUCKET --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

    # - name: Invalidate CloudFront distribution
    #   run: |
    #     aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}


#AKIA47NGPB6DB7XLRY7R
#eugnbQU3pLENlhYbe7IGekhzLAJYvsbZ/zVHGLdt