name: Build and deploy dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: get last commit message
      id: commit-message
      run: echo "::set-output name=commit::$(git log -1 --pretty=%B)"

    - name: test commit message
      id: test-commit
      run: |
        if ! ./checkCommit "${{ steps.commit-message.outputs.commit }}"; then
          echo "Commit message failed check"
          echo "COMMIT_CHECK=1" >> "$GITHUB_ENV"
        else
          echo "COMMIT_CHECK=0" >> "$GITHUB_ENV"
        fi
    
    - name: print env
      run: env
    - name: ssh
      if: env.COMMIT_CHECK == '0'
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: execute
      if: env.COMMIT_CHECK == '0'
      run: ssh -o "StrictHostKeyChecking=no" ec2-user@${{ secrets.SSH_HOST }} "./install.sh"
