name: Build and Deploy to discord webhook AWS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: get last commit message
      run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr '\n' ' ')" >> $GITHUB_ENV

    - name: ssh
      if: startsWith(env.COMMIT_MESSAGE, 'AUTO COMMIT')
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: execute
      if: startsWith(env.COMMIT_MESSAGE, 'AUTO COMMIT')
      run: ssh -o "StrictHostKeyChecking=no" ec2-user@${{ secrets.SSH_HOST }} "cd .discord_webhook && ./launch.sh"
